heme: advanced
skin: o2k7
plugins:
  - table
  - fullscreen
  - paste
  - print
  - template
  - searchreplace
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_buttons1_add:
  - fontselect
  - fontsizeselect
  - forecolor
  - backcolor
theme_advanced_buttons2_add_before:
  - cut
  - copy
  - paste
  - pastetext
  - pasteword
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - print
  - template
